language: go

go:
    - 1.4
    - 1.5
    - 1.6
    - 1.7

install:
    - go get github.com/upyun/go-sdk/upyun

script:
    - sudo apt-get update && sudo apt-get install -y dnsutils
    - dig v0.api.upyun.com
    - cd upyun && go test -v
