language: go

go:
  - 1.3
  - 1.4

install:
  - go get github.com/upyun/go-sdk/upyun

before_script:
  - export UPYUN_BUCKET=sdkfile
  - export UPYUN_USERNAME=tester
  - export UPYUN_PASSWORD=grjxv2mxELR3

script:
  - cd upyun && go test
