language: go

go:
    - "1.7"
    - "1.8"
    - "1.9"
    - "1.10"
    - "1.11"

install:
    - go get github.com/upyun/go-sdk/v3/upyun

script:
    - sudo apt-get update && sudo apt-get install -y dnsutils
    - dig v0.api.upyun.com
    - cd upyun && go test -v
